apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: cf-k8s-api
  name: proxy
spec:
  virtualhost:
    fqdn: API_URL
    tls:
      secretName: cf-k8s-api-ingress-cert
  routes:
  - conditions:
    - prefix: /
    services:
    - name: cf-k8s-api-svc
      port: 80
