# Adds namespace to all resources.
namespace: cf-k8s-api-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: cf-k8s-api-

resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- rbac

configMapGenerator:
- files:
  - cf_k8s_api_config.yaml
  name: config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cloudfoundry/cf-k8s-api
  newName: cf-k8s-api
  newTag: 22d0f1ff-94df-42ea-b414-d2f5a2407d2f
