# This is a basic workflow to help you get started with Actions

name: Test, Build, and Push image from main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*/**'
    - 'ci/Dockerfile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/cloudfoundry/cf-k8s-api-ci

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0' # The Go version to download (if necessary) and use.
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Unit Tests
        run: make test

  e2e-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    container: ghcr.io/cloudfoundry/cf-k8s-api-ci
    steps:
      - uses: actions/checkout@v2
        with:
          path: cf-k8s-api
      - uses: actions/checkout@v2
        with:
          repository: cloudfoundry/cf-k8s-controllers
          path: cf-k8s-controllers
      - uses: actions/checkout@v2
        with:
          repository: cloudfoundry-incubator/eirini-controller
          path: eirini-controller
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('cf-k8s-api/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - name: Run End to End Tests
        run: make test-e2e
        working-directory: ./cf-k8s-api

  # This workflow contains a single job called "build"
  build:
    needs: e2e-tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cloudfoundry/cf-k8s-api:latest
