# This is a basic workflow to help you get started with Actions

name: Run Tests on PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.
      - name: Check for reference yaml drift
        run: |
          make build-reference
          git diff --exit-code

  tests:
    needs: check-reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: cf-k8s-api
      - uses: actions/checkout@v2
        with:
          repository: cloudfoundry/cf-k8s-controllers
          path: cf-k8s-controllers
      - uses: actions/checkout@v2
        with:
          repository: cloudfoundry-incubator/eirini-controller
          path: eirini-controller
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('cf-k8s-api/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Run all tests
        run: make test
        working-directory: ./cf-k8s-api
